# Paths to respective directories for each step in the pipeline
fastq_dir: "/dartfs/rc/lab/R/RossB/RobitailleS/rnaseq_230925/raw_reads/"
trimmed_dir: "/dartfs/rc/lab/R/RossB/RobitailleS/rnaseq_230925/trimmed/"
alignment_dir: "/dartfs/rc/lab/R/RossB/RobitailleS/rnaseq_230925/alignment/"
htseq_counts_dir: "/dartfs/rc/lab/R/RossB/RobitailleS/rnaseq_230925/htseq_counts/"

samples:
  - WT1_min
  - WT1_pos
  - tetR1_min
  - tetR1_pos
  - WT3_min
  - WT3_pos
  - tetR3_min
  - tetR3_pos
  - WT4_min
  - WT4_pos
  - tetR4_min
  - tetR4_pos